[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"
authors = ["Eduard Bondarenko <edbond@gmail.com>"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.5.6"
anyhow = "1.0"
